## http://docs.pivotal.io/platform-automation/v2.1/reference/inputs-outputs.html#product-config

product-name: cf
product-properties:
  .cloud_controller.allow_app_ssh_access:
    value: true
  .cloud_controller.apps_domain:
    value: apps.pcfdemo.net
  .cloud_controller.default_app_memory:
    value: 1024
  .cloud_controller.default_app_ssh_access:
    value: true
  .cloud_controller.default_disk_quota_app:
    value: 1024
  .cloud_controller.default_quota_max_number_services:
    value: 1000
  .cloud_controller.default_quota_memory_limit_mb:
    value: 10240
  .cloud_controller.enable_custom_buildpacks:
    value: true
  .cloud_controller.encrypt_key:
    value: {}
  .cloud_controller.max_disk_quota_app:
    value: 2048
  .cloud_controller.max_file_size:
    value: 1024
  .cloud_controller.security_event_logging_enabled:
    value: false
  .cloud_controller.staging_timeout_in_seconds:
    value: 9000
  .cloud_controller.system_domain:
    value: system.pcfdemo.net
  .diego_brain.starting_container_count_maximum:
    value: 200
  .doppler.message_drain_buffer_size:
    value: 10000
  .ha_proxy.skip_cert_verify:
    value: true
  ...