## download director config
# http://docs.pivotal.io/platform-automation/v2.1/reference/inputs-outputs.html#director-config

az-configuration:
- name: az1
  clusters:
  - cluster: cluster1
    resource_pool: ""
  iaas_configuration_guid: 6552ba16572953313cea
- name: az2
  clusters:
  - cluster: cluster2
    resource_pool: ""
  iaas_configuration_guid: 6552ba16572953313cea
network-assignment:
  network:
    name: infra-network
  other_availability_zones: []
  singleton_availability_zone:
    name: az1
networks-configuration:
  icmp_checks_enabled: true
  networks:
 ...

